version: '3.9'

services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm
    container_name: yii2_php
    volumes:
      - ./fitbase_test:/app
    working_dir: /app
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
    depends_on:
      - mysql
    networks:
      - local_backend

  nginx:
    image: nginx:latest
    container_name: yii2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./fitbase_test:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - local_backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - local_backend

  mysql:
    image: mysql:8.0
    container_name: yii2_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2app
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    volumes:
      - mysql_data:/var/lib/mysql
      # init scripts: create extra DB and grants for tests
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - local_backend

  migrate:
    image: yiisoftware/yii2-php:8.2-fpm
    container_name: yii2_migrate
    working_dir: /app
    volumes:
      - ./fitbase_test:/app
    depends_on:
      - mysql
    entrypoint: >
      sh -c "
        echo 'â³ Waiting for MySQL...' &&
        sleep 10 &&
        echo 'ğŸš€ Running migrations for main DB...' &&
        php yii migrate --interactive=0 &&
        echo 'ğŸš€ Running migrations for test DB...' &&
        php yii_test migrate --interactive=0 
      "
    networks:
      - local_backend
      
networks:
  local_backend:
    driver: bridge

volumes:
  mysql_data:
    external: true
